version: '2'
 
services:

  orderer.voting.org:
    container_name: orderer.voting.org
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/voting.org/orderers/orderer.voting.org/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/voting.org/orderers/orderer.voting.org/tls/:/var/hyperledger/orderer/tls
    - orderer.voting.org:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
 
  peer0.station1.voting.org:
    container_name: peer0.station1.voting.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.station1.voting.org
      - CORE_PEER_ADDRESS=peer0.station1.voting.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.station1.voting.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.station1.voting.org:7051
      - CORE_PEER_LOCALMSPID=station1MSP
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_Vnet
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/station1.voting.org/peers/peer0.station1.voting.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/station1.voting.org/peers/peer0.station1.voting.org/tls:/etc/hyperledger/fabric/tls
        - peer0.station1.voting.org:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.station1.voting.org:
    container_name: peer1.station1.voting.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.station1.voting.org
      - CORE_PEER_ADDRESS=peer1.station1.voting.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.station1.voting.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.station1.voting.org:7051
      - CORE_PEER_LOCALMSPID=station1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/station1.voting.org/peers/peer1.station1.voting.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/station1.voting.org/peers/peer1.station1.voting.org/tls:/etc/hyperledger/fabric/tls
        - peer1.station1.voting.org:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053

  peer0.station2.voting.org:
    container_name: peer0.station2.voting.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.station2.voting.org
      - CORE_PEER_ADDRESS=peer0.station2.voting.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.station2.voting.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.station2.voting.org:7051
      - CORE_PEER_LOCALMSPID=station2MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/station2.voting.org/peers/peer0.station2.voting.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/station2.voting.org/peers/peer0.station2.voting.org/tls:/etc/hyperledger/fabric/tls
        - peer0.station2.voting.org:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
 
  peer1.station2.voting.org:
    container_name: peer1.station2.voting.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.station2.voting.org
      - CORE_PEER_ADDRESS=peer1.station2.voting.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.station2.voting.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.station2.voting.org:7051
      - CORE_PEER_LOCALMSPID=station2MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/station2.voting.org/peers/peer1.station2.voting.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/station2.voting.org/peers/peer1.station2.voting.org/tls:/etc/hyperledger/fabric/tls
        - peer1.station2.voting.org:/var/hyperledger/production    
    ports:
      - 10051:7051
      - 10053:7053
 
  peer0.station3.voting.org:
    container_name: peer0.station3.voting.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.station3.voting.org
      - CORE_PEER_ADDRESS=peer0.station3.voting.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.station3.voting.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.station3.voting.org:7051
      - CORE_PEER_LOCALMSPID=station3MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/station3.voting.org/peers/peer0.station3.voting.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/station3.voting.org/peers/peer0.station3.voting.org/tls:/etc/hyperledger/fabric/tls
        - peer0.station3.voting.org:/var/hyperledger/production  
    ports:
      - 11051:7051
      - 11053:7053
 
  peer1.station3.voting.org:
    container_name: peer1.station3.voting.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.station3.voting.org
      - CORE_PEER_ADDRESS=peer1.station3.voting.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.station3.voting.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.station3.voting.org:7051
      - CORE_PEER_LOCALMSPID=station3MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/station3.voting.org/peers/peer1.station3.voting.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/station3.voting.org/peers/peer1.station3.voting.org/tls:/etc/hyperledger/fabric/tls
        - peer1.station3.voting.org:/var/hyperledger/production    
    ports:
      - 12051:7051
      - 12053:7053
 
  peer0.station4.voting.org:
    container_name: peer0.station4.voting.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.station4.voting.org
      - CORE_PEER_ADDRESS=peer0.station4.voting.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.station4.voting.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.station4.voting.org:7051
      - CORE_PEER_LOCALMSPID=station4MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/station4.voting.org/peers/peer0.station4.voting.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/station4.voting.org/peers/peer0.station4.voting.org/tls:/etc/hyperledger/fabric/tls
        - peer0.station4.voting.org:/var/hyperledger/production    
    ports:
      - 13051:7051
      - 13053:7053
 
  peer1.station4.voting.org:
    container_name: peer1.station4.voting.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.station4.voting.org
      - CORE_PEER_ADDRESS=peer1.station4.voting.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.station4.voting.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.station4.voting.org:7051
      - CORE_PEER_LOCALMSPID=station4MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/station4.voting.org/peers/peer1.station4.voting.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/station4.voting.org/peers/peer1.station4.voting.org/tls:/etc/hyperledger/fabric/tls
        - peer1.station4.voting.org:/var/hyperledger/production    
    ports:
      - 14051:7051
      - 14053:7053
 
  peer0.GovermentAgency.voting.org:
    container_name: peer0.GovermentAgency.voting.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.GovermentAgency.voting.org
      - CORE_PEER_ADDRESS=peer0.GovermentAgency.voting.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.GovermentAgency.voting.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.GovermentAgency.voting.org:7051
      - CORE_PEER_LOCALMSPID=GovermentAgencyMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/GovermentAgency.voting.org/peers/peer0.GovermentAgency.voting.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/GovermentAgency.voting.org/peers/peer0.GovermentAgency.voting.org/tls:/etc/hyperledger/fabric/tls
        - peer0.GovermentAgency.voting.org:/var/hyperledger/production    
    ports:
      - 15051:7051
      - 15053:7053
 
  peer1.GovermentAgency.voting.org:
    container_name: peer1.GovermentAgency.voting.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.GovermentAgency.voting.org
      - CORE_PEER_ADDRESS=peer1.GovermentAgency.voting.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.GovermentAgency.voting.org:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.GovermentAgency.voting.org:7051
      - CORE_PEER_LOCALMSPID=GovermentAgencyMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/GovermentAgency.voting.org/peers/peer1.GovermentAgency.voting.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/GovermentAgency.voting.org/peers/peer1.GovermentAgency.voting.org/tls:/etc/hyperledger/fabric/tls
        - peer1.GovermentAgency.voting.org:/var/hyperledger/production    
    ports:
      - 16051:7051
      - 16053:7053
 
  
   